Bind: 0.0.0.0
Port: 9090
TimeDiff: 60
key: 123456
Interval: 3600

CertConfig:
  - CertMode: dns
    CertDomain: test.example.com
    Provider: cloudflare
    Email: test@test.com
    DNSEnv:
      CLOUDFLARE_EMAIL: YOUR_EMAIL
      CLOUDFLARE_API_KEY: YOUR_API_KEY