name: release

on:
  push:
    tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target: [i686, x86_64, arm, armhf, aarch64, mips, mipsel, mips64, mips64el, s390x, win32]
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake curl file libtool
      - name: Cross build (${{ matrix.target }})
        env:
          BUILD_TARGET: ${{ matrix.target }}
        run: |
          ./scripts/cross-build.sh
          mv build/ttyd build/ttyd.${{ matrix.target }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build/ttyd.${{ matrix.target }}
          allowUpdates: true
          draft: true
