name = "pb"
compatibility_date = "2023-01-28"

account_id = "1ddaf86dbca12e8f4fcaa76f32bb707d"
workers_dev = false
main = "src/index.js"

# config for default production environment
vars = { ENVIRONMENT = "production" }
route = { pattern = "shz.al", custom_domain = true }
kv_namespaces = [
  { binding = "PB", id = "cc398e983a234aa19de5ea6af571a483" },
]

[env.preview]
vars = { ENVIRONMENT = "preview" }
route = { pattern = "pb-preview.shz.al", custom_domain = true }
minify = false

kv_namespaces = [
  { binding = "PB", id = "f56ae0043abd4bb4ab61c52071bd9c7f" }
]

