name: 1
on:
  schedule:
    - cron: 30 */2 * * *
  workflow_dispatch:
jobs:
  build1:
    name: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/fscarmen/tools git1
    - name: Deploy git1
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git1
        target-folder: tools
        commit-message: Update
        clean: true
        single-commit: false
  build2:
    name: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/fscarmen/warp_unlock git2
    - name: Deploy git2
      uses: JamesIves/github-pages-deploy-action@v4.2.3    
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git2
        target-folder: warp_unlock
        commit-message: Update
        clean: true
        single-commit: false
  build3:
    name: 3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/fscarmen/warp git3
    - name: Deploy git3
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git3
        target-folder: warp
        commit-message: Update
        clean: true
        single-commit: false
  build4:
    name: 4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/xyTom/Url-Shorten-Worker git4
    - name: Deploy git4
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git4
        target-folder: url-shorten-worker
        commit-message: Update
        clean: true
        single-commit: false
  build5:
    name: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone -b gh-pages https://github.com/xyTom/Url-Shorten-Worker git5
    - name: Deploy git5
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git5
        target-folder: url-shorten-worker-pages
        commit-message: Update
        clean: true
        single-commit: false
  build6:
    name: 6
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/realByg/cfworker-kv-image-hosting git6
    - name: Deploy git6
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git6
        target-folder: cfworker-kv-image-hosting
        commit-message: Update
        clean: true
        single-commit: false
  build7:
    name: 7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/xiaoyang-sde/reflare-template git7
        cd git7 && mv .github github
    - name: Deploy git7
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git7
        target-folder: rocket-booster-template
        commit-message: Update
        clean: true
        single-commit: false
  build8:
    name: 8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/cloudflare/workers-chat-demo git8
    - name: Deploy git8
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git8
        target-folder: workers-chat-demo
        commit-message: Update
        clean: true
        single-commit: false
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
  build9:
    name: 9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/SharzyL/pastebin-worker git9
        cd git9 && mv .github github
    - name: Deploy git9
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git9
        target-folder: pastebin-worker
        commit-message: Update
        clean: true
        single-commit: false
  build10:
    name: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/mack-a/v2ray-agent git10
    - name: Deploy git10
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git10
        target-folder: v2ray-agent
        commit-message: Update
        clean: true
        single-commit: false
  build11:
    name: 11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/testnobody/azure-manager git11
    - name: Deploy git11
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git11
        target-folder: azure-manager
        commit-message: Update
        clean: true
        single-commit: false
  build12:
    name: 12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/zephyrchien/midori git12
        cd git12 && mv .github github
    - name: Deploy git12
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git12
        target-folder: midori
        commit-message: Update
        clean: true
        single-commit: false
  build13:
    name: 13
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/zephyrchien/tokio-tfo git13
        cd git13 && mv .github github
    - name: Deploy git13
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git13
        target-folder: tokio-tfo
        commit-message: Update
        clean: true
        single-commit: false
  build14:
    name: 14
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/zephyrchien/realm git14
        cd git14 && mv .github github
    - name: Deploy git14
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git14
        target-folder: realm
        commit-message: Update
        clean: true
        single-commit: false
  build15:
    name: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/mikf/gallery-dl git15
        cd git15 && mv .github github
    - name: Deploy git15
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git15
        target-folder: gallery-dl
        commit-message: Update
        clean: true
        single-commit: false
  build16:
    name: 16
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/JKme/cube git16
        cd git16 && mv .github github
    - name: Deploy git16
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git16
        target-folder: cube
        commit-message: Update
        clean: true
        single-commit: false
  build17:
    name: 17
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/tsl0922/ttyd git17
        cd git17 && mv .github github
    - name: Deploy git17
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git17
        target-folder: ttyd
        commit-message: Update
        clean: true
        single-commit: false
  build18:
    name: 18
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/rapiz1/rathole git18
        cd git18 && mv .github github
    - name: Deploy git18
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git18
        target-folder: rathole
        commit-message: Update
        clean: true
        single-commit: false
  build19:
    name: 19
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/julydate/acmeDeliver git19
        cd git19 && mv .github github
    - name: Deploy git19
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git19
        target-folder: acme-Server
        commit-message: Update
        clean: true
        single-commit: false
  build20:
    name: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone -b client https://github.com/julydate/acmeDeliver git20
    - name: Deploy git20
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git20
        target-folder: acme-Client
        commit-message: Update
        clean: true
        single-commit: false
