name: sync
on:
  schedule:
    - cron: 30 */2 * * *
  workflow_dispatch:
jobs:
  build1:
    name: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/harrisoff/onedrive-image-hosting git1
        cd git1 && mv .github github
    - name: Deploy git1
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git1
        target-folder: onedrive-image-hosting
        commit-message: Update
        clean: true
        single-commit: false
  build2:
    name: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clonehttps://github.com/iyear/E5SubBot git2
        cd git2 && mv .github github
    - name: Deploy git2
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: v6b
        git-config-email: 99478294+v6b@users.noreply.github.com
        branch: main
        folder: git2
        target-folder: E5SubBot
        commit-message: Update
        clean: true
        single-commit: false
